### ISSUE TITLE
Cant run latest version of contextio library on node v4.2.6

### ISSUE THREAD

**Issue by hamxabaig** [contextio/ContextIO-node#44]
Hey, thanks for this library. 

In latest version, use of `let or const` is used. But I think if you included this its a breaking change and major should be incremented. It caused our CI to break because we've `v4.2.6` of node.

https://github.com/contextio/ContextIO-node/blob/1c5820f87a5acb7b0987973c6c6c1b592ab39c9a/lib/2.0.js#L25-L28

Right now we'll use the old version of context io but what do you think guys ?

**Comment by AaronLaBrie** [comment]
Howdy! Sorry to hear your CI broke - I'd debated a bit on making this a major version change or a minor, but ultimately decided on minor since there were no changes to the actual functionality or interface ([PR](https://github.com/contextio/ContextIO-node/pull/40), [Release](https://github.com/contextio/ContextIO-node/releases/tag/v1.2.0)).

Maybe you've already investigated this, but enabling some es6 features with the `--harmony` flag might let you use future versions of the library. Here's a [jumping-off point](https://nodejs.org/en/docs/es6/) in case you haven't.

**Comment by AaronLaBrie** [comment]
Also, I _highly_ recommend working [Yarn](https://yarnpkg.com/en/) into your development/CI process. It's saved me a whole lot of trouble in situations like these.

**Comment by hamxabaig** [comment]
No worries, I've been already thinking about Yarn (already using it for local) but i was being a lazy potato. Will check it out. Though i didn't know that minor was solely based to change the ES version (no other functionalities)
Closing this since this was intentional and also some other people can save some mins looking at this issue ;)
Thanks
